<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ekin Kızıldaş - Gür Piren">
<meta name="dcterms.date" content="2025-05-14">

<title>Social Network - Assignment #2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Social_Network_2nd_Assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="Social_Network_2nd_Assignment_files/libs/quarto-html/quarto.js"></script>
<script src="Social_Network_2nd_Assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="Social_Network_2nd_Assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Social_Network_2nd_Assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="Social_Network_2nd_Assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Social_Network_2nd_Assignment_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Social_Network_2nd_Assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Social_Network_2nd_Assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Social_Network_2nd_Assignment_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#libraries" id="toc-libraries" class="nav-link active" data-scroll-target="#libraries"><span class="header-section-number">1</span> Libraries</a></li>
  <li><a href="#tasks" id="toc-tasks" class="nav-link" data-scroll-target="#tasks"><span class="header-section-number">2</span> Tasks</a>
  <ul class="collapse">
  <li><a href="#choose-a-network" id="toc-choose-a-network" class="nav-link" data-scroll-target="#choose-a-network"><span class="header-section-number">2.1</span> Choose a network</a></li>
  <li><a href="#import-network-data" id="toc-import-network-data" class="nav-link" data-scroll-target="#import-network-data"><span class="header-section-number">2.2</span> Import network data</a></li>
  </ul></li>
  <li><a href="#link-prediction-project" id="toc-link-prediction-project" class="nav-link" data-scroll-target="#link-prediction-project"><span class="header-section-number">3</span> Link Prediction Project</a>
  <ul class="collapse">
  <li><a href="#delete-a-fraction-of-real-edges-randomly-remove-10-20-of-edges-using-delete_edges-in-igraph.-create-a-table-of-deleted-positive-and-non-existing-negative-links-with-sample-for-negative-class." id="toc-delete-a-fraction-of-real-edges-randomly-remove-10-20-of-edges-using-delete_edges-in-igraph.-create-a-table-of-deleted-positive-and-non-existing-negative-links-with-sample-for-negative-class." class="nav-link" data-scroll-target="#delete-a-fraction-of-real-edges-randomly-remove-10-20-of-edges-using-delete_edges-in-igraph.-create-a-table-of-deleted-positive-and-non-existing-negative-links-with-sample-for-negative-class."><span class="header-section-number">3.1</span> Delete a fraction of real edges: Randomly remove 10-20% of edges using delete_edges() in igraph. Create a table of deleted (positive) and non-existing (negative) links with sample() for negative class.</a></li>
  <li><a href="#generate-proximitysimilarity-metrics-compute-heuristics-common-neighbors-jaccard-adamic-adar-for-all-links-using-similarity-functions-in-igraph-or-custom-calculations." id="toc-generate-proximitysimilarity-metrics-compute-heuristics-common-neighbors-jaccard-adamic-adar-for-all-links-using-similarity-functions-in-igraph-or-custom-calculations." class="nav-link" data-scroll-target="#generate-proximitysimilarity-metrics-compute-heuristics-common-neighbors-jaccard-adamic-adar-for-all-links-using-similarity-functions-in-igraph-or-custom-calculations."><span class="header-section-number">3.2</span> Generate proximity/similarity metrics: Compute heuristics (common neighbors, Jaccard, Adamic-Adar) for all links using similarity() functions in igraph or custom calculations.</a></li>
  <li><a href="#modeling-part" id="toc-modeling-part" class="nav-link" data-scroll-target="#modeling-part"><span class="header-section-number">3.3</span> Modeling Part</a></li>
  <li><a href="#evaluation-of-model" id="toc-evaluation-of-model" class="nav-link" data-scroll-target="#evaluation-of-model"><span class="header-section-number">3.4</span> Evaluation of model</a></li>
  <li><a href="#potential-improvements" id="toc-potential-improvements" class="nav-link" data-scroll-target="#potential-improvements"><span class="header-section-number">3.5</span> Potential Improvements</a></li>
  </ul></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference"><span class="header-section-number">4</span> Reference</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Social Network - Assignment #2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ekin Kızıldaş - Gür Piren </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 14, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="libraries" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="libraries"><span class="header-section-number">1</span> Libraries</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(archive)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph) </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidygraph)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(extrafont)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fmsb)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tasks" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="tasks"><span class="header-section-number">2</span> Tasks</h2>
<section id="choose-a-network" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="choose-a-network"><span class="header-section-number">2.1</span> Choose a network</h3>
<p>Marvel Universe social network, 2002. The network shows Marvel characters as being linked if they jointly appear in the same Marvel comic book.</p>
<p>The dataset can be accessed through this <a href="https://networks.skewed.de/net/marvel_universe">link</a></p>
<p>Number of nodes: 19.428 Number of edges: 95.497</p>
</section>
<section id="import-network-data" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="import-network-data"><span class="header-section-number">2.2</span> Import network data</h3>
<p>One important thing to note about our network is that it is a bipartite network. We have discovered this after consulting the professor, and found out that the first 6.486 rows represent the character nodes while the rest shows the comic books in which characters appear.</p>
<p>We will address the issue using bipartite projection, which will help us separate the characters nodes from the comic book nodes, eventually providing us with the robust results when assessing different types of similarity metrics. To not spoil all the fun just yet, let’s move onto data cleaning part.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>marvel_nodes <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/nodes.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">quote =</span> <span class="st">"</span><span class="sc">\"</span><span class="st">"</span>, <span class="at">fill =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>marvel_links <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/edges.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Data cleaning for the node coordinates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># to get proper x and y coordinates</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>marvel_nodes<span class="sc">$</span>x_cor <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">str_extract</span>(marvel_nodes<span class="sc">$</span>X_pos,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"-?</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+"</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>marvel_nodes<span class="sc">$</span>y_cor <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">str_extract_all</span>(marvel_nodes<span class="sc">$</span>X_pos,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                                                 <span class="st">"-?</span><span class="sc">\\</span><span class="st">d+</span><span class="sc">\\</span><span class="st">.</span><span class="sc">\\</span><span class="st">d+"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">sapply</span>(<span class="st">`</span><span class="at">[</span><span class="st">`</span>, <span class="dv">2</span>))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># we don't need the X_pos anymore</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>marvel_nodes<span class="sc">$</span>X_pos <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Renaming the columns and starting the index column from 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>marvel_nodes <span class="ot">&lt;-</span> marvel_nodes <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">id =</span> X..index,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">character_name =</span> name) <span class="sc">|&gt;</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id =</span> id <span class="sc">+</span> <span class="dv">1</span>) <span class="co"># for best indexing practice</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cleaning the names in the character name column</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>marvel_nodes <span class="ot">&lt;-</span> marvel_nodes <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">character_name =</span> <span class="fu">str_replace_all</span>(character_name, <span class="st">"/"</span>, <span class="st">" "</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">character_name =</span> <span class="fu">str_trim</span>(<span class="fu">str_replace</span>(character_name, <span class="st">"^(</span><span class="sc">\\</span><span class="st">w+),</span><span class="sc">\\</span><span class="st">s*([</span><span class="sc">\\</span><span class="st">w</span><span class="sc">\\</span><span class="st">s]+)$"</span>, <span class="st">"</span><span class="sc">\\</span><span class="st">2 </span><span class="sc">\\</span><span class="st">1"</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">character_name =</span> <span class="fu">str_replace_all</span>(character_name, <span class="st">"[^[:alnum:]</span><span class="sc">\\</span><span class="st">s]"</span>, <span class="st">""</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Applying the same indexing logic to ‘marvel_links’ where character co-appearances are stored.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>marvel_links <span class="ot">&lt;-</span> marvel_links <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">source =</span> X..source,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">target =</span> target)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>marvel_links <span class="ot">&lt;-</span> marvel_links <span class="sc">|&gt;</span> </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">source =</span> source <span class="sc">+</span> <span class="dv">1</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">target =</span> target <span class="sc">+</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code builds a bipartite graph from marvel_links, keeping only edges between characters and comic books. (The first 6.486 rows belong to characters, whereas the rest is comic books)</p>
<p>We then create the bipartite graph and tag nodes as character (FALSE) or comic book (TRUE).</p>
<p>Lastly, we project the bipartite graph into a character–character network, where two characters are connected if they appear in the same comic book.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># only keep proper bipartite edges: one from each type</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>marvel_links_bip <span class="ot">&lt;-</span> marvel_links <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((source <span class="sc">&lt;=</span> <span class="dv">6486</span> <span class="sc">&amp;</span> target <span class="sc">&gt;</span> <span class="dv">6486</span>) <span class="sc">|</span> (source <span class="sc">&gt;</span> <span class="dv">6486</span> <span class="sc">&amp;</span> target <span class="sc">&lt;=</span> <span class="dv">6486</span>))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># recreating the graph with only valid bipartite edges</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>bipartite_graph <span class="ot">&lt;-</span> <span class="fu">graph_from_data_frame</span>(marvel_links_bip, <span class="at">vertices =</span> marvel_nodes, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># tagging the nodes</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(bipartite_graph)<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">seq_along</span>(<span class="fu">V</span>(bipartite_graph)) <span class="sc">&gt;</span> <span class="dv">6486</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co"># character-character network</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>projections <span class="ot">&lt;-</span> <span class="fu">bipartite_projection</span>(bipartite_graph)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>network_graph <span class="ot">&lt;-</span> projections<span class="sc">$</span>proj1  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Visualization</strong></p>
<p>Visualising the network after projection.</p>
<p>The network shows a densely connected core surrounded by many weakly connected nodes, suggesting a small group of central characters who frequently co-appear, while many others have limited connections. The scattered periphery and disconnected components imply minor characters, and the layout highlights the strong centralization.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>layout <span class="ot">&lt;-</span> <span class="fu">layout_with_fr</span>(network_graph) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(network_graph, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.label =</span> <span class="cn">NA</span>, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.size =</span> <span class="dv">2</span>, </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.color =</span> <span class="st">"red"</span>, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.color =</span> <span class="st">"black"</span>, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.width =</span> <span class="fl">0.5</span>, </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">layout =</span> layout)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Social_Network_2nd_Assignment_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="link-prediction-project" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="link-prediction-project"><span class="header-section-number">3</span> Link Prediction Project</h2>
<section id="delete-a-fraction-of-real-edges-randomly-remove-10-20-of-edges-using-delete_edges-in-igraph.-create-a-table-of-deleted-positive-and-non-existing-negative-links-with-sample-for-negative-class." class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="delete-a-fraction-of-real-edges-randomly-remove-10-20-of-edges-using-delete_edges-in-igraph.-create-a-table-of-deleted-positive-and-non-existing-negative-links-with-sample-for-negative-class."><span class="header-section-number">3.1</span> Delete a fraction of real edges: Randomly remove 10-20% of edges using delete_edges() in igraph. Create a table of deleted (positive) and non-existing (negative) links with sample() for negative class.</h3>
<p>The below code visualizes the process of preparing data for link prediction on the Marvel network in three steps: first, it plots the original network with all connections; then, it removes 15% of the edges, highlights them in gray, and plots this modified network; finally, it creates a reduced network by deleting those edges, generates a negative class of non-existing links, and plots the reduced network. The positive class consists of the removed edges, while the negative class includes an equal number of randomly sampled non-existing node pairs. The plots use node positions from x_cor and y_cor, with red nodes, black edges, and no labels for clarity.</p>
<p><strong>Original Network:</strong> The full Marvel character-character projection network created from the bipartite character-comic network, showing all connections between characters based on shared comic appearances.</p>
<p><strong>Network with Removed Edges:</strong> The same network but with 10–20% of its edges highlighted in gray to indicate which links have been selected for removal. This helps visualize which character relationships are targeted for deletion while still preserving the original structure. (However, due to high volyme of nodes, the gray ones are not very visible)</p>
<p><strong>Reduced Network:</strong> The resulting network after actually deleting the selected edges. It displays only the remaining connections among characters, making it sparser and visually showing the impact of the edge removal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># to ensure the 1x3 layout of three networks - original, network with removed edges, and reduced network</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># original network</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(network_graph,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.label =</span> <span class="cn">NA</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.size =</span> <span class="dv">2</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.color =</span> <span class="st">"red"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.color =</span> <span class="st">"black"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.width =</span> <span class="fl">0.5</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">layout =</span> layout)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># randomly removing 10-20% of edges</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>remove_frac <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="fl">0.10</span>, <span class="fl">0.20</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>remove_edges <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ecount</span>(network_graph), <span class="at">size =</span> <span class="fu">round</span>(remove_frac <span class="sc">*</span> <span class="fu">ecount</span>(network_graph)))</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>edges <span class="ot">&lt;-</span> <span class="fu">as_data_frame</span>(network_graph, <span class="at">what =</span> <span class="st">"edges"</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>positive_class <span class="ot">&lt;-</span> edges[remove_edges, <span class="fu">c</span>(<span class="st">"from"</span>, <span class="st">"to"</span>)]</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co"># coloring the removed edges gray for visualization</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(network_graph)<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="st">"black"</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(network_graph)<span class="sc">$</span>color[remove_edges] <span class="ot">&lt;-</span> <span class="st">"gray"</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="co"># second plot, the network with removed edges</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(network_graph,</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.label =</span> <span class="cn">NA</span>,</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.size =</span> <span class="dv">2</span>,</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.color =</span> <span class="st">"red"</span>,</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.width =</span> <span class="fl">0.5</span>,</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>     <span class="at">layout =</span> layout)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="co"># removing edges to form the reduced graph </span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>graph_reduced <span class="ot">&lt;-</span> <span class="fu">delete_edges</span>(network_graph, remove_edges)</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="co"># saampling negative class (non-edges)</span></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>sample_non_edges <span class="ot">&lt;-</span> <span class="cf">function</span>(gr, n) {</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>  non_edges <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">from =</span> <span class="fu">integer</span>(), <span class="at">to =</span> <span class="fu">integer</span>())</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>  <span class="cf">while</span> (<span class="fu">nrow</span>(non_edges) <span class="sc">&lt;</span> n) {</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    v1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">vcount</span>(gr), <span class="dv">1</span>)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    v2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">vcount</span>(gr), <span class="dv">1</span>)</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (v1 <span class="sc">!=</span> v2 <span class="sc">&amp;&amp;</span> <span class="sc">!</span><span class="fu">are_adjacent</span>(gr, v1, v2)) {</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>      non_edges <span class="ot">&lt;-</span> <span class="fu">rbind</span>(non_edges, <span class="fu">data.frame</span>(<span class="at">from =</span> <span class="fu">V</span>(gr)<span class="sc">$</span>name[v1], <span class="at">to =</span> <span class="fu">V</span>(gr)<span class="sc">$</span>name[v2]))</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>  non_edges</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>negative_class <span class="ot">&lt;-</span> <span class="fu">sample_non_edges</span>(graph_reduced, <span class="fu">nrow</span>(positive_class))</span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a><span class="co"># third plot, the reduced graph (after deletion)</span></span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a><span class="fu">E</span>(graph_reduced)<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="st">"black"</span></span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(graph_reduced,</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.label =</span> <span class="cn">NA</span>,</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.size =</span> <span class="dv">2</span>,</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.color =</span> <span class="st">"red"</span>,</span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>     <span class="at">edge.width =</span> <span class="fl">0.5</span>,</span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>     <span class="at">layout =</span> layout)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Social_Network_2nd_Assignment_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="generate-proximitysimilarity-metrics-compute-heuristics-common-neighbors-jaccard-adamic-adar-for-all-links-using-similarity-functions-in-igraph-or-custom-calculations." class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="generate-proximitysimilarity-metrics-compute-heuristics-common-neighbors-jaccard-adamic-adar-for-all-links-using-similarity-functions-in-igraph-or-custom-calculations."><span class="header-section-number">3.2</span> Generate proximity/similarity metrics: Compute heuristics (common neighbors, Jaccard, Adamic-Adar) for all links using similarity() functions in igraph or custom calculations.</h3>
<p><strong>Common Neighbours</strong></p>
<p>The common neighbours method counts the number of shared neighbors between two nodes, indicating similarity through mutual connections.</p>
<p>In our approach, we used ‘Dice’ similarity to calculate common neighbors, adjusting it by incorporating the <strong>degree</strong> of the nodes. This method, we believe, will help us weight common neighbors based on node connectivity, offering a more balanced measure that accounts for node importance. We wanted to provide a more balanced view by accounting for the relative importance of nodes by doing this.</p>
<p>After ensuring that the node identifiers in both the positive and negative link sets are stored as integers, we calculate three node similarity matrices (Dice, Jaccard, and Adamic-Adar) for all node pairs in the reduced graph.</p>
<p>We calculate common neighbors after applying Dice similarity to incorporate both the shared neighbors and the degree of the nodes. This allows us to weight common neighbors more effectively, ensuring that more connected nodes have a proportional influence, which enhances the accuracy of our link prediction. Let’s hope it was a good choice!</p>
<p>These similarities are used to assess how likely two unconnected nodes might form a link. After that, the positive and negative examples are combined into a single dataset with a class label indicating whether a pair is a real (1) or fake (0) link.</p>
<p>Finally, a custom similarity score based on common neighbors is computed using the Dice similarity and the average degree of the two nodes. Then we will move onto other similarity metrics such as Jaccard and Adamic-Adar in the next chunks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># making sure our positive/negative classes are integers</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>positive_class <span class="ot">&lt;-</span> positive_class <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">from =</span> <span class="fu">as.integer</span>(from),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">to   =</span> <span class="fu">as.integer</span>(to))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>negative_class <span class="ot">&lt;-</span> negative_class <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">from =</span> <span class="fu">as.integer</span>(from),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">to   =</span> <span class="fu">as.integer</span>(to))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># precomputing ALL three similarity matrices on the reduced graph</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>dice_mat    <span class="ot">&lt;-</span> <span class="fu">similarity</span>(graph_reduced, <span class="at">method =</span> <span class="st">"dice"</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>jaccard_mat <span class="ot">&lt;-</span> <span class="fu">similarity</span>(graph_reduced, <span class="at">method =</span> <span class="st">"jaccard"</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>aa_mat      <span class="ot">&lt;-</span> <span class="fu">similarity</span>(graph_reduced, <span class="at">method =</span> <span class="st">"invlogweighted"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co"># combining all</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(positive_class, <span class="at">class =</span> <span class="dv">1</span>),</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(negative_class, <span class="at">class =</span> <span class="dv">0</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>)    </span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co"># for the common neighbours </span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>metrics<span class="sc">$</span>common_neighbors <span class="ot">&lt;-</span> <span class="fu">mapply</span>(<span class="cf">function</span>(u, v) {</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>  dice_mat[u, v] <span class="sc">*</span> (<span class="fu">degree</span>(graph_reduced, u) <span class="sc">+</span> <span class="fu">degree</span>(graph_reduced, v)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>}, metrics<span class="sc">$</span>from, metrics<span class="sc">$</span>to)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Jaccard</strong></p>
<p>The Jaccard method measures similarity as the ratio of shared neighbors to total unique neighbors of two nodes, normalizing for network size. Let’s calculate that too:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>metrics<span class="sc">$</span>jaccard <span class="ot">&lt;-</span> <span class="fu">mapply</span>(<span class="cf">function</span>(u, v) {</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  jaccard_mat[u, v]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>}, metrics<span class="sc">$</span>from, metrics<span class="sc">$</span>to)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Adamic-Adar</strong></p>
<p>The Adamic-Adar method weights shared neighbors by the inverse log of their degrees, emphasizing connections through less-connected nodes. Onto calculating that:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>metrics<span class="sc">$</span>adamic_adar <span class="ot">&lt;-</span> <span class="fu">mapply</span>(<span class="cf">function</span>(u, v) {</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  aa_mat[u, v]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>}, metrics<span class="sc">$</span>from, metrics<span class="sc">$</span>to)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>For the results</strong></p>
<p>The results from the table indicate pairs of nodes in the Marvel network that share common neighbors but are not directly connected (class = 1).</p>
<p>The common_neighbors column (5 to 70) shows the number of shared neighbors between pairs. These pairs, despite not being connected, have some level of overlap in their network of connections.</p>
<p>The jaccard scores (0.008 to 0.17) represent the ratio of shared neighbors relative to the total number of unique neighbors between the pair. Lower values (like 0.008) suggest minimal overlap in their neighbor relationships, while higher values (such as 0.17) show a more significant overlap of neighbors.</p>
<p>The adamic_adar scores (0.96 to 11.98) indicate the importance of shared neighbors by weighing them based on the inverse logarithm of their degree. Higher scores (11.98) imply that the shared neighbors are less connected overall and are more valuable in predicting a possible connection between the pair.</p>
<p>This variability in the similarity metrics across pairs will be useful for a classifier to determine which pairs are more likely to form direct links in the network, based on their proximity and shared neighbors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(metrics,<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   from   to class common_neighbors    jaccard adamic_adar
1  5295 6342     1               22 0.22916667   5.3420855
2  3428 3919     1               15 0.15151515   3.0268054
3  2544 5046     1              195 0.17711172  38.8690887
4  2557 5330     1               27 0.02278481   4.9652026
5  1393 5278     1                2 0.25000000   0.6133733
6  2764 4881     1               25 0.11210762   4.0833679
7   154 2152     1               24 0.02547771   4.7342048
8  4415 5439     1                4 0.00968523   1.5919997
9   478 3509     1               20 0.08097166   3.2312833
10  906 3625     1               18 0.11320755   3.4345286</code></pre>
</div>
</div>
<p><strong>Preferential Attachment</strong></p>
<p>‘Preferential Attachment’ is a metric that predicts if two nodes might connect by multiplying the number of connections (degrees) each node has—a higher number means they’re more likely to connect because nodes with more connections tend to form new ones more easily.</p>
<p>The table shows pairs of nodes in the Marvel network with no direct connection (class = 1), evaluated using the preferential attachment metric.</p>
<p>The pref_attach values (5,940 to 26,625) indicate the likelihood of forming a connection based on node degrees. Higher values (such as 26,625) suggest a greater potential for a link due to higher degrees, while lower values (5,940) indicate a weaker potential.</p>
<p>This metric helps the classifier assess which pairs might form connections based on node connectivity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(network_graph)<span class="sc">$</span>name <span class="ot">&lt;-</span> <span class="fu">as.character</span>(<span class="fu">V</span>(network_graph)) </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>metrics<span class="sc">$</span>pref_attach <span class="ot">&lt;-</span> <span class="fu">mapply</span>(<span class="cf">function</span>(u, v) {</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  u <span class="ot">&lt;-</span> <span class="fu">as.character</span>(u)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">as.character</span>(v)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (u <span class="sc">%in%</span> <span class="fu">V</span>(network_graph)<span class="sc">$</span>name <span class="sc">&amp;</span> v <span class="sc">%in%</span> <span class="fu">V</span>(network_graph)<span class="sc">$</span>name) {</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">degree</span>(network_graph, <span class="at">v =</span> u) <span class="sc">*</span> <span class="fu">degree</span>(network_graph, <span class="at">v =</span> v)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="dv">0</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>}, metrics<span class="sc">$</span>from, metrics<span class="sc">$</span>to)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(metrics <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>common_neighbors, <span class="sc">-</span>jaccard, <span class="sc">-</span>adamic_adar))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  from   to class pref_attach
1 5295 6342     1        3296
2 3428 3919     1        3230
3 2544 5046     1      440496
4 2557 5330     1       61778
5 1393 5278     1          60
6 2764 4881     1       20468</code></pre>
</div>
</div>
</section>
<section id="modeling-part" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="modeling-part"><span class="header-section-number">3.3</span> Modeling Part</h3>
<p>Next, three classifiers which are logistic regression, a decision tree (CART), and random forest was trained by using our four heuristics (common neighbors, Jaccard, Adamic–Adar and preferential attachment) as input features.</p>
<p>All models were evaluated via 5-fold cross-validation in the caret package, optimizing for AUC (ROC) and saving out of fold predictions for comparison.</p>
<p><strong>Logistic Regression (GLM)</strong> achieved an average ROC of 0.994, with sensitivity around 98% (effectively identifying most true links) but a specificity of 95% (showing a reasonable ability to avoid false positives).</p>
<p><strong>Decision Tree (rpart)</strong> reached an average ROC of 0.979, with sensitivity around 96% and specificity of 97%, offering a balanced performance with slightly fewer false positives than GLM, while being easier to interpret.</p>
<p><strong>Random Forest (RF)</strong> scored an average ROC of 0.995, with sensitivity around 97% and specificity of 98%, outperforming both GLM and Decision Tree, thanks to the power of ensemble learning for higher robustness and accuracy.</p>
<p>This comparison shows that logistic regression excels in identifying true connections with high sensitivity, the decision tree offers a clear and interpretable decision-making process with balanced sensitivity and specificity, and random forest delivers the best performance by capturing complex interactions and achieving the highest accuracy across all metrics.</p>
<p>The scatter plot from the second output compares the ROC scores of three models.The Tree model has the lowest ROC score at around 0.980, with a wider confidence interval, indicating more variability. GLM and Random Forest models perform better, with ROC scores around 0.994 and 0.995, respectively, and narrower confidence intervals, suggesting more consistent performance. Overall, GLM and RF outperform the Tree model in terms of predictive accuracy, as indicated by their higher ROC values. (as previously explained)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># features &amp; target</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> metrics <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(common_neighbors, jaccard, adamic_adar, pref_attach)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">factor</span>(metrics<span class="sc">$</span>class, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"no"</span>,<span class="st">"yes"</span>))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 5-fold cross validation setup, saving probabilities and using ROC for model selection</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">method           =</span> <span class="st">"cv"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">number           =</span> <span class="dv">5</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">classProbs       =</span> <span class="cn">TRUE</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">summaryFunction  =</span> twoClassSummary,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">savePredictions  =</span> <span class="st">"final"</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="co"># for logistic regression model</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>model_glm_lp <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">x         =</span> X,</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">y         =</span> y,</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">method    =</span> <span class="st">"glm"</span>,</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">family    =</span> <span class="fu">binomial</span>(),</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric    =</span> <span class="st">"ROC"</span>,</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> ctrl</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="co"># for decision tree </span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>model_dt <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">x         =</span> X,</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">y         =</span> y,</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">method    =</span> <span class="st">"rpart"</span>,</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric    =</span> <span class="st">"ROC"</span>,</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl =</span> ctrl,</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">tuneLength =</span> <span class="dv">10</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a><span class="co"># for random forest</span></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>model_rf <span class="ot">&lt;-</span> <span class="fu">train</span>(</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">x          =</span> X,</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">y          =</span> y,</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">method     =</span> <span class="st">"rf"</span>,</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">metric     =</span> <span class="st">"ROC"</span>,</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">trControl  =</span> ctrl,</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">tuneLength =</span> <span class="dv">5</span>,</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>  <span class="at">ntree      =</span> <span class="dv">500</span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>note: only 3 unique complexity parameters in default grid. Truncating the grid to 3 .</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># for the results</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>resamps <span class="ot">&lt;-</span> <span class="fu">resamples</span>(<span class="fu">list</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">GLM  =</span> model_glm_lp,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Tree =</span> model_dt,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">RF   =</span> model_rf</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(resamps))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
summary.resamples(object = resamps)

Models: GLM, Tree, RF 
Number of resamples: 5 

ROC 
          Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's
GLM  0.9940235 0.9941422 0.9945542 0.9945640 0.9950031 0.9950970    0
Tree 0.9836663 0.9840183 0.9850921 0.9849603 0.9853920 0.9866326    0
RF   0.9942904 0.9943109 0.9945150 0.9946609 0.9946391 0.9955489    0

Sens 
          Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's
GLM  0.9822148 0.9824520 0.9829222 0.9833983 0.9841082 0.9852941    0
Tree 0.9639554 0.9658525 0.9675047 0.9684094 0.9717742 0.9729602    0
RF   0.9684535 0.9691651 0.9705882 0.9706857 0.9720180 0.9732037    0

Spec 
          Min.   1st Qu.    Median      Mean   3rd Qu.      Max. NA's
GLM  0.9547071 0.9582543 0.9592030 0.9592545 0.9594498 0.9646584    0
Tree 0.9694023 0.9720114 0.9729602 0.9744802 0.9788949 0.9791321    0
RF   0.9793643 0.9793692 0.9807875 0.9807419 0.9815034 0.9826850    0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bwplot</span>(resamps, <span class="at">metric =</span> <span class="st">"ROC"</span>, <span class="at">main =</span> <span class="st">"ROC Comparison Across Models"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Social_Network_2nd_Assignment_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="evaluation-of-model" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="evaluation-of-model"><span class="header-section-number">3.4</span> Evaluation of model</h3>
<p>Logistic Regression achieved an AUC of 0.994, showing strong ranking ability, with high precision (98%) and recall (95%), meaning it accurately identifies most links but still allows some false negatives.</p>
<p>Decision Tree reached an AUC of 0.980, slightly lower but still strong, with balanced precision (96%) and recall (97%), offering interpretable rules and solid overall performance.</p>
<p>Random Forest scored the highest AUC of 0.995 and the best accuracy (97%), with balanced precision (97%) and recall (98%), showing excellent predictive performance by modeling complex patterns in the network.</p>
<p><strong>Feature importance - and what they suggest</strong></p>
<p>In the context of a social network, feature importance analysis tells us which network-based features (like number of shared neighbors, Jaccard similarity, Adamic-Adar score, or preferential attachment) are most influential in predicting whether a link (relationship) exists between two nodes (in our case, characters).</p>
<p>In short, feature importance shows which structural patterns in the network are most predictive of connections. So let’s move onto the first model:</p>
<p>In the decision tree model, Adamic-adar is the most important feature, meaning it contributed the most to splitting the data and making accurate predictions. Common Neighbors also played a strong role, while Jaccard and Preferential Attachment were less influential. This suggests the tree relies heavily on nuanced shared neighbor information to detect links in the social network.</p>
<p>In the random forest model, Adamic-adar stands out as the most important feature by far, indicating it’s the strongest predictor of links in the network. Common neighbors contributes moderately, while Jaccard and especially Preferential Attachmnt play a much smaller role. This shows that the model focuses on deeper structural similarity over basic connection counts.</p>
<p>In the logistic regression model, Adamic-adar and Common neighbours are the most influential features, suggesting they strongly affect the likelihood of a predicted link. Jaccard and Preferential Attachment have much lower importance, indicating they contribute less to the model’s decisions. This reflects a reliance on raw and weighted counts of shared neighbors rather than relative overlap or node popularity.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logistic regression</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>pred_glm <span class="ot">&lt;-</span> model_glm_lp<span class="sc">$</span>pred</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>cm_glm   <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_glm<span class="sc">$</span>pred, pred_glm<span class="sc">$</span>obs, <span class="at">positive =</span> <span class="st">"yes"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>auc_glm  <span class="ot">&lt;-</span> <span class="fu">roc</span>(pred_glm<span class="sc">$</span>obs, pred_glm<span class="sc">$</span>yes)<span class="sc">$</span>auc</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># decision tree</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>pred_dt <span class="ot">&lt;-</span> model_dt<span class="sc">$</span>pred</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>cm_dt   <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_dt<span class="sc">$</span>pred, pred_dt<span class="sc">$</span>obs, <span class="at">positive =</span> <span class="st">"yes"</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>auc_dt  <span class="ot">&lt;-</span> <span class="fu">roc</span>(pred_dt<span class="sc">$</span>obs, pred_dt<span class="sc">$</span>yes)<span class="sc">$</span>auc</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># random forest</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>pred_rf <span class="ot">&lt;-</span> model_rf<span class="sc">$</span>pred <span class="sc">%&gt;%</span> <span class="fu">filter</span>(mtry <span class="sc">==</span> model_rf<span class="sc">$</span>bestTune<span class="sc">$</span>mtry)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>cm_rf   <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_rf<span class="sc">$</span>pred, pred_rf<span class="sc">$</span>obs, <span class="at">positive =</span> <span class="st">"yes"</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>auc_rf  <span class="ot">&lt;-</span> <span class="fu">roc</span>(pred_rf<span class="sc">$</span>obs, pred_rf<span class="sc">$</span>yes)<span class="sc">$</span>auc</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co"># table for model metrics</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>metrics_new <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model     =</span> <span class="fu">c</span>(<span class="st">"Logistic Regression"</span>, <span class="st">"Decision Tree"</span>, <span class="st">"Random Forest"</span>),</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">AUC       =</span> <span class="fu">c</span>(auc_glm, auc_dt, auc_rf),</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Accuracy  =</span> <span class="fu">c</span>(cm_glm<span class="sc">$</span>overall[<span class="st">"Accuracy"</span>],</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>                cm_dt<span class="sc">$</span>overall[<span class="st">"Accuracy"</span>],</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>                cm_rf<span class="sc">$</span>overall[<span class="st">"Accuracy"</span>]),</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Precision =</span> <span class="fu">c</span>(cm_glm<span class="sc">$</span>byClass[<span class="st">"Precision"</span>],</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>                cm_dt<span class="sc">$</span>byClass[<span class="st">"Precision"</span>],</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>                cm_rf<span class="sc">$</span>byClass[<span class="st">"Precision"</span>]),</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">Recall    =</span> <span class="fu">c</span>(cm_glm<span class="sc">$</span>byClass[<span class="st">"Recall"</span>],</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>                cm_dt<span class="sc">$</span>byClass[<span class="st">"Recall"</span>],</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>                cm_rf<span class="sc">$</span>byClass[<span class="st">"Recall"</span>])</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(metrics_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  Model                 AUC Accuracy Precision Recall
  &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1 Logistic Regression 0.995    0.971     0.983  0.959
2 Decision Tree       0.985    0.971     0.969  0.974
3 Random Forest       0.995    0.976     0.971  0.981</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Feature Importance</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># decision tree</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>varImp_dt <span class="ot">&lt;-</span> <span class="fu">varImp</span>(model_dt, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(varImp_dt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rpart variable importance

                 Overall
adamic_adar        18711
common_neighbors   17415
jaccard            11654
pref_attach        10363</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(varImp_dt, <span class="at">main =</span> <span class="st">"Feature Importance - Decision Tree"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Social_Network_2nd_Assignment_files/figure-html/model-evaluation-and-importance-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fandom forest</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>varImp_rf <span class="ot">&lt;-</span> <span class="fu">varImp</span>(model_rf, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(varImp_rf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rf variable importance

                 Overall
adamic_adar      10917.4
common_neighbors  6832.6
jaccard           2581.6
pref_attach        696.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(varImp_rf, <span class="at">main =</span> <span class="st">"Feature Importance - Random Forest"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Social_Network_2nd_Assignment_files/figure-html/model-evaluation-and-importance-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">## logistic regression</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>varImp_lg <span class="ot">&lt;-</span> <span class="fu">varImp</span>(model_glm_lp, <span class="at">scale =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(varImp_lg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>glm variable importance

                 Overall
adamic_adar       49.608
common_neighbors  42.415
pref_attach       13.084
jaccard            9.144</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(varImp_lg, <span class="at">main =</span> <span class="st">"Feature Importance - LG"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Social_Network_2nd_Assignment_files/figure-html/model-evaluation-and-importance-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="potential-improvements" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="potential-improvements"><span class="header-section-number">3.5</span> Potential Improvements</h3>
<p>Improving link prediction involves refining the model, data, or features to better capture the patterns that explain how links form in a network. To make this, we can:</p>
<p><strong>Feature expansion - feature engineering</strong></p>
<p>Our current features (common neighbors, jaccard, adamic_adar, preferential attachment) used in the assignment are classic heuristics. While effective, they can only capture local structure. We can improve prediction by including more advanced or diverse features, such as:</p>
<ul>
<li><p>Node centrality measures (degree, betweenness, closeness)</p></li>
<li><p>Community detection results (whether the nodes are in the same cluster)</p></li>
<li><p>Temporal or contextual features if available (time of interaction, node type)</p></li>
<li><p>Graph embeddings (Node2Vec, DeepWalk) to capture latent structural info.</p></li>
</ul>
<p><strong>Addressing class imbalance</strong></p>
<p>If the number of links is much smaller than non-links, this imbalance may bias models we use.</p>
<ul>
<li><p>Downsampling the majority class or upsampling the minority</p></li>
<li><p>Using performance metrics sensitive to imbalance (like AUC, F1)</p></li>
<li><p>Trying cost-sensitive models that penalize false negatives more</p></li>
</ul>
<p><strong>Model tuning and algorithm selection</strong></p>
<p>Although random forest performed slightly better overall, we could still benefit from some of the following:</p>
<ul>
<li><p>Hyperparameter tuning (more trees, which would adjust the depth)</p></li>
<li><p>Trying other models like XGBoost and LightGBM</p></li>
<li><p>Ensembling models to combine strengths of multiple approaches (We have seen/done this in Advanced Modelling class!)</p></li>
</ul>
<p>Lastly, considering the challenges we faced because of the bipartite structure of the network:</p>
<p><strong>Network-level data quality</strong></p>
<p>Next time, we might want to check the following before getting hands-on to ensure our network data is well structured</p>
<ul>
<li><p>Are there missing or noisy links?</p></li>
<li><p>Are all nodes relevant?</p></li>
<li><p>Would pruning weak or indirect links help improve the analysis?</p></li>
</ul>
</section>
</section>
<section id="reference" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="reference"><span class="header-section-number">4</span> Reference</h2>
<p>R. Alberich, J. Miro-Julia, and F. Rossello, “Marvel Universe looks almost like a real social network.” arxiv:cond-mat/0202174 (2002)., http://arxiv.org/abs/cond-mat/0202174</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>